### ISSUE TITLE
Add package from LAMMPS

### ISSUE THREAD

**Issue by quentinf30** [ComputationalPhysics/atomify-lammps#408]
Hi,

I downloaded the software ( latest mac version). I open the .dmg file and put the application it in my application folder. I tried to use it on one of my script of LAMMPS and it did not work. It could not call a package of LAMMPS. Do you know how to solve that problem? I tried to do what it is written in the readme file but I could find the folder you were talking about.

Quentin

**Comment by andeplane** [comment]
Hi,

To change contents of LAMMPS, you actually have to build Atomify from source as of now. If you follow the **How to build** instructions, you should then be able to find the folder.

Which package was missing? I could also include it in a later release (there will be one later this week).

**Comment by quentinf30** [comment]
Thanks, I will try the How to build. 

The package I am looking for is for the class2 bond_type

**Comment by andeplane** [comment]
Could you try the latest 2.2a preview? https://github.com/ovilab/atomify/releases

It should have the class2 package installed.

**Comment by quentinf30** [comment]
I am reinstalling LAMMPS right now. I will do it when it will be done

**Comment by quentinf30** [comment]
I reinstall LAMMPS and I followed the steps to install atomify (the 2.2a) with the How to Build steps. I have an error when I type python configure.py: python: can't open file 'generateExamples.py': [Errno 2] No such file or directory. And because of that when I tried to run/build atomify with Qt Creator I have an error

**Comment by andeplane** [comment]
The 2.2a does not need to do these steps. You should be able to just download it and run it with class2 type potentials.

If you want to build it yourself, you would need to download the source code (not from the v2.2a link because those files are broken, but GitHub puts them there anyway). Just follow the instructions which says that you need to clone the repository with
`git clone --recursive https://github.com/ovilab/atomify.git`
instead of downloading the 2.2a code. Following these steps carefully should work!
